### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by Enrick3344** [Awzaw/NoTP#1]
You could add more command that are blocked! Like /tpa and /call which are 2 new command for Tp action on EssentialsPe. I can make a pull request for that and A functionality that saves when the player run the command. So Saves name in a config. Pull request could be possible there too. 
-Enrick

**Comment by InspectorGadget** [comment]
It's actually worth PR-ing, Awzaw is busy. He might merge if the code is neat. :)

**Comment by Enrick3344** [comment]
@InspectorGadget I will do when I will have time! I'm glad to Help!:)

**Comment by Enrick3344** [comment]
@InspectorGadget My pull request Is made.
